<?php

namespace App\Patterns\Decorator;

class DecoratedService implements DecorationInterface
{
    private BaseService $baseService;

    public function __construct(BaseService $baseService)
    {
        $this->baseService = $baseService;
    }

    public function doSomething(): void
    {
        echo 'This is an extra step, generated by the decorator '.__CLASS__.', by the method '.__METHOD__.'<br>';

        $this->baseService->doSomething();
    }

    public function doAnotherThing(): void
    {
        echo 'This is an extra step, generated by the decorator '.__CLASS__.', by the method '.__METHOD__.'<br>';

        $this->baseService->doAnotherThing();

        echo 'This is another extra step, executed afterward.<br>';
    }
}
