<?php

namespace App\Patterns\Decorator;

class DecoratedService implements DecorationInterface
{
    private BaseService $baseService;

    public function __construct(BaseService $baseService)
    {
        $this->baseService = $baseService;
    }

    public function doSomething(): string
    {
        $text = 'This is an extra step, generated by the decorator '.__CLASS__.', by the method '.__METHOD__;

        return $text."\n".$this->baseService->doSomething();
    }

    public function doAnotherThing(): string
    {
        $text = 'This is an extra step, generated by the decorator '.__CLASS__.', by the method '.__METHOD__;

        $text .= "\n".$this->baseService->doAnotherThing();

        return $text."\nThis is another extra step, executed afterward.";
    }
}
