name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image and run container
        run: |
          docker compose build --no-cache
          docker compose up --wait

      - name: Check code quality
        run: |
          docker exec -i designpatterns_php_dev vendor/bin/php-cs-fixer check
          docker exec -i designpatterns_php_dev vendor/bin/phpstan
